In [2]:
import numpy as np  
import tensorflow as tf  

# Prepare XOR gate dataset  
xor_table = np.array([[0, 0, 0],  
                      [1, 0, 1],  
                      [0, 1, 1],  
                      [1, 1, 0]], dtype=np.float32)  

x_train = xor_table[:, :2]  # Inputs: x1, x2  
y_train = xor_table[:, 2:]  # Labels: y  

# Define a neural network model for XOR
class LogicGate(tf.keras.Model):  
    def __init__(self):  
        super(LogicGate, self).__init__()  
        self.dense1 = tf.keras.layers.Dense(4, activation='relu')  # Hidden layer  
        self.dense2 = tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer  

    def call(self, inputs):  
        x = self.dense1(inputs)  
        return self.dense2(x)  

# Initialize and compile the model  
model = LogicGate()  
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),  
              loss='binary_crossentropy',  
              metrics=['accuracy'])  

# Train the model  
model.fit(x_train, y_train, epochs=1000, verbose=0)  

# Evaluate and print results  
y_pred = model.predict(x_train).round().astype(np.uint8)  

print("Predicted Truth Table:")  
print(np.column_stack((xor_table[:, :2], y_pred)))  


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Predicted Truth Table:
[[0. 0. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]
